<a href="https://colab.research.google.com/github/ollihansen90/Mathe-SH-ML/blob/main/Blatt1_Vorlage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Aufgabe 3

1.   Programmiere die Matrix-Vektor-Multiplikation per Hand.
2.   Programmiere eine zweite Version mit vertauschter Schleifenreihenfolge.
3.   Nutze *numpy* für die Matrix-Vektor-Multiplikation.
4.   Nutze zum Beispiel die Library *time* um die Laufzeiten zu vergleichen. Dafür kann die selbe Berechnung einfach $100\, 000$ Mal oder öfter durchgeführt werden.






In [ ]:
# Wir programmieren die Matrix-Vektor-Multiplikation zuerst per Hand

import numpy as np

def matvec1(A,B):
  # A ist Matrix und B ein Vektor

  # Zuerst muessen wir die Groeße der Matrizen bestimmen 
  #shapeA= #ToDo
  #shapeB= #ToDo

  # Wir testen, ob für die Größen die Matrix-Vektor-Multiplikation erfuellt ist.
  # (optional)
  '''
  if(...)
  '''
  # Wir geben die MAtrix C
  return 0

def matvec2(A,B):
  # Wir programmieren die gleiche Funktion wie eben,
  # nur mit anderer Schleifenreihenfolge

  return 0


In [ ]:
# Wir testen unsere Implementierung
A = np.zeros((2,3))
B = np.zeros((3,1))

A[0,0] = 1
A[0,1] = 2
A[0,2] = 4
A[1,0] = 2
A[1,1] = 4
A[1,2] = 5
B[0,0] = 2
B[1,0] = 4
B[2,0] = 5
print('variante1',matvec1(A,B))
print('variante2',matvec2(A,B))

variante1 0
variante2 0


Die Vektoren sollten in beiden Fällen [[30.][45.]] in diesem oder einem ähnlichem Format sein

In [ ]:
# Nun machen wir den Geschwindigkeitstest
# Dafuer erstellen wir Aufgaben mit vielen Rechnungen
import random
n = 10000 # Zahl kann fuer laengere/kuerzere Rechnung angepasst werden
A = np.zeros((n,n))
B = np.zeros((n,1))
# Zufallsvektoren erstllen
for i in range(0,n):
  for j in range(0,n):
    A[i,j] = random.random()
  B[i,0] = random.random()

print('A',A)

A [[0.37308096 0.94732974 0.87174242 ... 0.99305992 0.78187775 0.22646776]
 [0.06302271 0.41706512 0.23024126 ... 0.7494299  0.3687625  0.49796124]
 [0.52097518 0.73523372 0.55345853 ... 0.16745235 0.26134429 0.63443267]
 ...
 [0.30573378 0.69200495 0.51444443 ... 0.81948391 0.09129994 0.38783477]
 [0.54522554 0.67598237 0.06001934 ... 0.0408317  0.05431723 0.99856397]
 [0.23764968 0.65175829 0.03301844 ... 0.62737497 0.28988686 0.46843043]]


In [ ]:
import time

start_time = time.time()
matvec1(A,B)
end_time = time.time()
print('elapsed time',end_time-start_time)

start_time = time.time()
matvec2(A,B)
end_time = time.time()
print('elapsed time',end_time-start_time)

start_time = time.time()
# ToDo: Matrix-Vektor-Multiplikation aus Python nutzen
end_time = time.time()
print('elapsed time',end_time-start_time)

elapsed time 9.250640869140625e-05
elapsed time 0.00011515617370605469
elapsed time 5.91278076171875e-05
